### PR TITLE
Fix: No response to errors in plot user group modifications

### LINKED ISSUE #4104: TagResolver / sendMessage problem
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

With using `/p trust <same player = plot owner>` on my own plot, I down't get a message.

[/Core/src/main/java/com/plotsquared/core/command/Trust.java#L115-L121](https://github.com/RedstoneFuture/PlotSquared/blob/587a286d05dad11e4d2a1a2280819e62ee258627/Core/src/main/java/com/plotsquared/core/command/Trust.java#L115-L121)
```java
                        player.sendMessage(
                                TranslatableCaption.of("member.already_added"),
                                TagResolver.resolver(
                                        "value",
                                        Tag.inserting(PlayerManager.resolveName(uuid).toComponent(player))
                                )
                        );
```

Maybe the TagResolver has a problem.

Same with `/p trust <same player = plot owner>` and `/p add <already added player>`, `/p trust <already trusted player>`, `/p ban <already banned player>`.

### To Reproduce

1. Get a plot.
2. `/p trust <your name>`

### Expected behaviour

Message: "member.already_added"

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9dcdad83acbb44e8820ad964447bbbd0

### PlotSquared Version

PlotSquared v7.0.0-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #4104

## Description
- Deprecates the old static methods to get a Caption from a users UUID
- Added new method in PlayerManager to retrieve a Caption from a users UUID non-blocking
- Removed thread-blocking and fast-timeout messages / captions
- Added utility methods to send messages to players with asynchronously resolved TagResolvers

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Review by dordsor21 — APPROVED** [review]

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 1]
```diff
@@ -211,6 +216,27 @@ public static void getUUIDsFromString(
         return StaticCaption.of(name);
     }
 
+    public CompletableFuture<Caption> getUsernameCaption(@Nullable UUID uuid) {
```
Comment (SirYwell) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:219]: Should be documented

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 2]
```diff
@@ -211,6 +216,27 @@ public static void getUUIDsFromString(
...
+        }
+        if (uuid.equals(DBFunc.EVERYONE)) {
+            return CompletableFuture.completedFuture(TranslatableCaption.of("info.everyone"));
+        }
+        if (uuid.equals(DBFunc.SERVER)) {
+            return CompletableFuture.completedFuture(TranslatableCaption.of("info.server"));
+        }
+        if (playerMap.containsKey(uuid)) {
+            return CompletableFuture.completedFuture(StaticCaption.of(playerMap.get(uuid).getName()));
+        }
```
Comment (SirYwell) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:231]: This seems to be a general problem in this class, but this is subject to a race condition. It would be safer to call get directly and do a null check then.

As a follow-up to this PR, it might be a good idea to generally a) either specify which threads are allowed to interact with which methods safely in this class, and/or b) guard access to the playerMap by RW locking or use a concurrent map.

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java (hunk 1 above)
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java]: my bad

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 3]
```diff
@@ -169,7 +172,9 @@ public static void getUUIDsFromString(
      * @return A caption containing either the name, {@code None}, {@code Everyone} or {@code Unknown}
      * @see #resolveName(UUID, boolean)
      * @since 6.4.0
+     * @deprecated Don't unnecessarily block threads and utilize playerMap - see {@link #getUsernameCaption(UUID)}
      */
+    @Deprecated
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:177]:
```suggestion
    @Deprecated(since = "TODO")
```

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 4]
```diff
@@ -181,7 +186,9 @@ public static void getUUIDsFromString(
      * @param blocking If the operation should block the current thread for {@link Settings.UUID#BLOCKING_TIMEOUT} milliseconds
      * @return A caption containing either the name, {@code None}, {@code Everyone} or {@code Unknown}
      * @since 6.4.0
+     * @deprecated Don't unnecessarily block threads and utilize playerMap - see {@link #getUsernameCaption(UUID)}
      */
+    @Deprecated
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:191]:
```suggestion
    @Deprecated(since = "TODO")
```

**Review by NotMyFault — COMMENTED** [review]
Some optional feedback
