### PR TITLE
Restriction: Adding "weaving-death-place" flag

### LINKED ISSUE #4517: Protection problem: Weaving status effect spawn blocks in roads and other plots
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

If a player receives the [Weaving status effect](https://minecraft.wiki/w/Weaving) and dies somewhere in the world, [cobwebs](https://minecraft.wiki/w/Cobweb) will be spawned at this point, regardless of their building permissions or other restrictions.

_Tested with Paper 1.21.1-14-master@9ab644e (2024-08-14T12:52:20Z) for Minecraft 1.21.1_

### To Reproduce

1. get the "weaving effet" via any kind of potion
2. go to another plot or in the road
3. will be killed or die by yourself in any way

### Expected behaviour

Do not spawn cobwebs. Only if the player is allowed to build. I recommend using a new flag.

### Screenshots / Videos

grafik

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4558b8ec1f80443fbebb48aad69defea

### PlotSquared Version

PlotSquared version 7.3.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by RedstoneFuture**
## Overview
This PR adds the "weaving-death-place" flag to prevent spawning of cobwebs on death by the [Weaving status effect](https://minecraft.wiki/w/Weaving).

Fixes #4517

## Description
- adding new flag "weaving-death-place" (default `false`)
- adding checks in the `EntityChangeBlockEvent`

The default value is “false”, because in my opinion it is rarely intended that the death of an entity on its own plot (including its own death) should spawn cobwebs on the plot (or other plots or the plot path). Especially because the status effect can be maintained by external factors (`minecraft:lingering_potion`). That makes the behavior so special that I wanted to handle it in a new custom flag rather than using an existing flag.

Only since 1.21.x are there status effects that spawn or change blocks on death. I will expand the restriction of wind-charge in another PR to improve the restriction for the new 1.21 features / behaviors.

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java [hunk 1]
```diff
@@ -32,11 +32,7 @@
 import com.plotsquared.core.plot.Plot;
 import com.plotsquared.core.plot.PlotArea;
 import com.plotsquared.core.plot.PlotHandler;
-import com.plotsquared.core.plot.flag.implementations.DisablePhysicsFlag;
-import com.plotsquared.core.plot.flag.implementations.EntityChangeBlockFlag;
-import com.plotsquared.core.plot.flag.implementations.ExplosionFlag;
-import com.plotsquared.core.plot.flag.implementations.InvincibleFlag;
-import com.plotsquared.core.plot.flag.implementations.ProjectileChangeBlockFlag;
```
Comment (PierreSchwang) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java:39]: Don't optimize imports, we don't use wildcard-imports. (https://github.com/IntellectualSites/PlotSquared/blob/main/.editorconfig#L70)

File: Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java [hunk 2]
```diff
@@ -19,101 +19,7 @@
...
-import com.plotsquared.core.plot.flag.implementations.TitlesFlag;
-import com.plotsquared.core.plot.flag.implementations.UntrustedVisitFlag;
-import com.plotsquared.core.plot.flag.implementations.UseFlag;
-import com.plotsquared.core.plot.flag.implementations.VehicleBreakFlag;
-import com.plotsquared.core.plot.flag.implementations.VehicleCapFlag;
-import com.plotsquared.core.plot.flag.implementations.VehiclePlaceFlag;
-import com.plotsquared.core.plot.flag.implementations.VehicleUseFlag;
-import com.plotsquared.core.plot.flag.implementations.VillagerInteractFlag;
-import com.plotsquared.core.plot.flag.implementations.VineGrowFlag;
-import com.plotsquared.core.plot.flag.implementations.WeatherFlag;
```
Comment (PierreSchwang) [inline Core/src/main/java/com/plotsquared/core/plot/flag/GlobalFlagContainer.java:116]: same as above

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java [hunk 3]
```diff
@@ -243,6 +239,32 @@ public void onEntityFall(EntityChangeBlockEvent event) {
...
+        PlotArea area = location.getPlotArea();
+        if (area == null) {
+            return;
+        }
+        Plot plot = area.getOwnedPlotAbs(location);
+
+        if (plot == null || !plot.getFlag(WeavingDeathPlace.class)) {
+            event.setCancelled(true);
+            if (plot != null) {
+                plot.debug("Falling block event was cancelled because weaving-death-place = false");
```
Comment (PierreSchwang) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java:263]: not a falling block

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java [hunk 4]
```diff
@@ -243,6 +239,32 @@ public void onEntityFall(EntityChangeBlockEvent event) {
...
+            return;
+        }
+        Location location = BukkitUtil.adapt(block.getLocation());
+        PlotArea area = location.getPlotArea();
+        if (area == null) {
+            return;
+        }
+        Plot plot = area.getOwnedPlotAbs(location);
+
+        if (plot == null || !plot.getFlag(WeavingDeathPlace.class)) {
```
Comment (PierreSchwang) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java:260]: In case of `null`-plot, handle road flags (`PlotFlagUtil.isAreaRoadFlagsAndFlagEquals`)

**Review by PierreSchwang — CHANGES_REQUESTED** [review]

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java (hunk 1 above)
Comment (RedstoneFuture) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java]: Oh, okay. Thanks.

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java (hunk 4 above)
Comment (RedstoneFuture) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java]: Now, I use the same checks as `onDamage(EntityDamageEvent event)` below with separate handling of the road flags.

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java [hunk 5]
```diff
@@ -244,24 +244,21 @@ public void onWeavingEffect(EntityChangeBlockEvent event) {
...
-            if (plot != null) {
-                plot.debug("Falling block event was cancelled because weaving-death-place = false");
+        Plot plot = location.getOwnedPlot();
+        if (plot == null) {
+            if (PlotFlagUtil.isAreaRoadFlagsAndFlagEquals(area, WeavingDeathPlace.class, false)) {
+                event.setCancelled(true);
             }
+            return;
+        }
+        if (plot.getFlag(WeavingDeathPlace.class)) {
```
Comment (PierreSchwang) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java:264]: that should be `!plot.getFlag` I guess?

Comment (RedstoneFuture) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java]: That's right. Sorry.

**Review by SirYwell — APPROVED** [review]
Looks good. Please also open a PR to add the flag to the documentation (https://github.com/IntellectualSites/documentation/blob/main/plotsquared/plot-flags.md). Thanks!

**Review by NotMyFault — APPROVED** [review]
