### PR TITLE
Fix home command reset

### LINKED ISSUE #4294: /plot sethome none doesnt reset to default location
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Resetting the plothome with /plot sethome none doesnt reset the home to the default location

### To Reproduce

- claim a plot
- set plothome (/p sethome)
- reset plothome (/p sethome none)

### Expected behaviour

Home position should be reset to default location.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a7fcb735f056463b9aca86f128562df5

### PlotSquared Version

7.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by OneLiteFeather**
## Overview
This PR should fix the missing reset happening while /p sethome none was executed. I had help with @TheMeinerLP which found the underlying solution together with me, as I am not a great developer with basic sql knowledge yet.

Fixes #4294 

## Description
- We fixed the setposition method with the default value and added a comment too to give other developers a hint to look it up on the statement. Also we added a location not null check because the issue lies within the equals implementation.

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

File: Core/src/main/java/com/plotsquared/core/plot/Plot.java [hunk 1]
```diff
@@ -1483,7 +1483,7 @@ private Location toHomeLocation(Location bottom, BlockLoc relativeHome) {
      */
     public void setHome(BlockLoc location) {
         Plot plot = this.getBasePlot(false);
-        if (BlockLoc.ZERO.equals(location) || BlockLoc.MINY.equals(location)) {
+        if (location != null && (BlockLoc.ZERO.equals(location) || BlockLoc.MINY.equals(location))) {
```
Comment (PierreSchwang) [inline Core/src/main/java/com/plotsquared/core/plot/Plot.java:1486]: The null check should not be required as we don't call equals on the nullable object itself

**Review by PierreSchwang — APPROVED** [review]
The one comment, which is not a dealbreaker but not really required.

No idea who introduced the default value as "DEFAULT" instead of just making the column nullable?

**Review by NotMyFault — APPROVED** [review]
