### PR TITLE
Only load world cofigurations if WorldEdit has fully enabled (safe to do)

### LINKED ISSUE #3664: Can't use default flags with block categories for standard world defined by server.properties
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When using the servers default world as a plot world with a default flag containing a block category (e.g. `#signs`), the PlotArea for that world is loaded before the world itself is loaded.
WorldEdit initializes the registries containing the categories etc after the first WorldInitEvent. Therefor the registries aren't filled at that moment and the default flag parsing throws an error.

### To Reproduce

1. Set the world `world` as the default word in server.properties
2. Use `world` as a plot world
3. Configure the plotworld to have a default use-flag with a block category (e.g. #signs)

### Expected behaviour

The flag should be parsed

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

-

### PlotSquared Version

-

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #3664

### CODE REVIEW

**Comment by NotMyFault** [comment]
Using the following setup and having a plotworld set in the server.properties file, I receive the stacktrace still: https://athion.net/ISPaster/paste/view/e1d19d707217430b9c7e57593783c743

**Comment by dordsor21** [comment]
I asked pierre to test and didn't say it didn't work ¯\_(ツ)_/¯

**Comment by dordsor21** [comment]
So the whole queryCapability stuff is just completely useless for seeing if capabilities are actually valid yet

File: Core/src/main/java/com/plotsquared/core/PlotSquared.java [hunk 1]
```diff
@@ -1574,6 +1580,13 @@ public void registerCaptionMap(
         return this.plotListener;
     }
 
+    /**
+     * Get if the {@link PlatformReadyEvent} has been sent by WE. There is no way to query this within WE itself.
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/PlotSquared.java:1584]:
```suggestion
     * Get if the {@link PlatformReadyEvent} has been sent by WorldEdit. There is no way to query this within WorldEdit itself.
     * @since TODO
```

File: Core/src/main/java/com/plotsquared/core/PlotSquared.java [hunk 2]
```diff
@@ -1596,4 +1609,14 @@ public enum SortType {
         DISTANCE_FROM_ORIGIN
     }
 
+    private final class WEPlatformReadyListener {
+
+        @Subscribe(priority = EventHandler.Priority.VERY_EARLY)
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/PlotSquared.java:1614]:
```suggestion
        @SuppressWarnings("unused")
        @Subscribe(priority = EventHandler.Priority.VERY_EARLY)
```

**Review by NotMyFault — COMMENTED** [review]
Otherwise, LGTM, working as expected.

**Review by PierreSchwang — APPROVED** [review]
Works perfectly fine for me

**Review by NotMyFault — APPROVED** [review]
Addressing my own concern here, this is now good to go.
