### PR TITLE
fix: attempt to recover from IllegalStateException when restoring block tags

### LINKED ISSUE #3801: plot regenallroads Bug
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

---- Minecraft Crash Report ----

Time: 9/14/22, 6:49 PM
Description: Exception generating new chunk
```
java.lang.IllegalStateException: The blockState must be placed to call this method
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84)
	at app//net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274)
	at app//org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.applyBiomeDecoration(CustomChunkGenerator.java:272)
	at app//net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93)
	at app//net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212)
	at app//net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$38(ChunkTracker.java:1326)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at app//net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1324)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at app//net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58)
	at app//net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87)
	at app//net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141)
	at app//net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```
-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187)
	at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316)
	at PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84)
	at app//net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274)
	at app//org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.applyBiomeDecoration(CustomChunkGenerator.java:272)
	at app//net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93)
	at app//net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212)

-- Chunk to be generated --
Details:
	Location: -1,30
	Position hash: 133143986175
	Generator: org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator@774a964a
Stacktrace:
	at app//net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$38(ChunkMap.java:1326)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at app//net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$40(ChunkMap.java:1324)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at app//net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,78,-96), Section: (at 0,14,0 in 7,4,-6; chunk contains blocks 112,0,-96 to 127,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 112790 game time, 36285 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 47086 (now: false), thunder time: 35896 (now: false)
	Known server brands: Paper
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1645)
	at app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490)
	at app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282)
	at app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 4.19.0-21-amd64
	Java Version: 17.0.4.1, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 763917440 bytes (728 MiB) / 1635778560 bytes (1560 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E31220 @ 3.10GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: MGA G200EH
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0533
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9046.19
	Virtual memory used (MB): 3066.91
	Swap memory total (MB): 1049.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx12288M -Xms1024M
	CraftBukkit Information: 
   Running: Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) true
   Plugins: { FastAsyncWorldEdit v2.4.5 com.sk89q.worldedit.bukkit.WorldEditPlugin [Empire92, MattBDev, IronApollo, dordsor21, NotMyFault], PlotSquared v6.9.4-Premium com.plotsquared.bukkit.BukkitPlatform [Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault, SirYwell],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING bStats-Metrics: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING ForkJoinPool-5-worker-13: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623), java.base@17.0.4.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)], TIMED_WAITING pool-6-thread-1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Netty Epoll Server IO #2: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:176), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Netty Epoll Server IO #1: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:176), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.4.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], TIMED_WAITING Server thread: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), app//net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:144), app//net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:133), app//net.minecraft.server.level.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:680), app//net.minecraft.world.level.World.getChunkAt(World.java:534), app//net.minecraft.world.level.World.getType(World.java:873), FastAsyncWorldEdit-Bukkit-2.4.5.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_17_R1_2.PaperweightFaweWorldNativeAccess.notifyNeighbors(PaperweightFaweWorldNativeAccess.java:184), FastAsyncWorldEdit-Bukkit-2.4.5.jar//com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_17_R1_2.PaperweightFaweWorldNativeAccess.notifyNeighbors(PaperweightFaweWorldNativeAccess.java:36), FastAsyncWorldEdit-Bukkit-2.4.5.jar//com.sk89q.worldedit.internal.wna.WorldNativeAccess.markAndNotifyBlock(WorldNativeAccess.java:184), FastAsyncWorldEdit-Bukkit-2.4.5.jar//com.sk89q.worldedit.internal.wna.WorldNativeAccess.setBlock(WorldNativeAccess.java:94), FastAsyncWorldEdit-Bukkit-2.4.5.jar//com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:525), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.BukkitQueueCoordinator.setWorldBlock(BukkitQueueCoordinator.java:264), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.BukkitQueueCoordinator.lambda$enqueue$2(BukkitQueueCoordinator.java:176), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.BukkitQueueCoordinator$$Lambda$6695/0x0000000801e4e298.accept(Unknown Source), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.queue.BukkitChunkCoordinator.run(BukkitChunkCoordinator.java:178), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44), app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101), app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483), app//net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567), app//net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490), app//net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483), app//net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282), app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319), app//net.minecraft.server.MinecraftServer$$Lambda$3652/0x00000008013cd788.run(Unknown Source), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Notification Thread: [], TIMED_WAITING Common-Cleaner: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.4.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], WAITING Snooper Timer: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.Object.wait(Object.java:338), java.base@17.0.4.1/java.util.TimerThread.mainLoop(Timer.java:537), java.base@17.0.4.1/java.util.TimerThread.run(Timer.java:516)], WAITING pool-20-thread-4: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING pool-20-thread-2: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Netty Epoll Server IO #3: [app//io.netty.channel.epoll.Native.epollWait0(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:176), app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 264: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Paper RegionFile IO Thread: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Timer-0: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.Object.wait(Object.java:338), java.base@17.0.4.1/java.util.TimerThread.mainLoop(Timer.java:537), java.base@17.0.4.1/java.util.TimerThread.run(Timer.java:516)], WAITING Paper Async Chunk Task Thread #0: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], RUNNABLE Server console handler: [java.base@17.0.4.1/java.io.FileInputStream.readBytes(Native Method), java.base@17.0.4.1/java.io.FileInputStream.read(FileInputStream.java:276), java.base@17.0.4.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:282), java.base@17.0.4.1/java.io.BufferedInputStream.read(BufferedInputStream.java:343), java.base@17.0.4.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270), java.base@17.0.4.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313), java.base@17.0.4.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188), java.base@17.0.4.1/java.io.InputStreamReader.read(InputStreamReader.java:177), java.base@17.0.4.1/java.io.BufferedReader.fill(BufferedReader.java:162), java.base@17.0.4.1/java.io.BufferedReader.readLine(BufferedReader.java:329), java.base@17.0.4.1/java.io.BufferedReader.readLine(BufferedReader.java:396), app//net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180), app//net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143), app//net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:113)], WAITING pool-13-thread-1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING bStats-Metrics: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 1 - PlotSquared: [java.base@17.0.4.1/java.lang.Thread.sleep(Native Method), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.database.SQLManager.lambda$new$0(SQLManager.java:220), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.database.SQLManager$$Lambda$4898/0x0000000801a2e7e0.run(Unknown Source), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39), PlotSquared-Bukkit-6.9.4-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44), app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101), app//org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57), app//com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Reference Handler: [java.base@17.0.4.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.4.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.4.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], WAITING pool-20-thread-3: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Paper Watchdog Thread: [java.base@17.0.4.1/java.lang.Thread.sleep(Native Method), app//org.spigotmc.WatchdogThread.run(WatchdogThread.java:243)], TIMED_WAITING process reaper: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), app//com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Craft Scheduler Thread - 262: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING WorldEdit Session Manager: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.util.TimerThread.mainLoop(Timer.java:563), java.base@17.0.4.1/java.util.TimerThread.run(Timer.java:516)], TIMED_WAITING Craft Scheduler Thread - 263: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), app//org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), app//org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], WAITING pool-20-thread-1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING ForkJoinPool-5-worker-14: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623), java.base@17.0.4.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)], TIMED_WAITING Cleaner-0: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.4.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], RUNNABLE Worker-Main-1: [java.base@17.0.4.1/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.4.1/java.lang.Thread.getAllStackTraces(Thread.java:1662), app//org.bukkit.craftbukkit.v1_17_R1.CraftCrashReport.get(CraftCrashReport.java:33), app//org.bukkit.craftbukkit.v1_17_R1.CraftCrashReport.get(CraftCrashReport.java:17), app//net.minecraft.SystemReport.a(SystemReport.java:65), app//net.minecraft.CrashReport.<init>(CrashReport.java:36), app//net.minecraft.CrashReport.a(CrashReport.java:246), app//net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$38(PlayerChunkMap.java:1334), app//net.minecraft.server.level.PlayerChunkMap$$Lambda$5291/0x0000000801bb6470.apply(Unknown Source), app//com.mojang.datafixers.util.Either$Left.map(Either.java:38), app//net.minecraft.server.level.PlayerChunkMap.lambda$scheduleChunkGeneration$40(PlayerChunkMap.java:1324), app//net.minecraft.server.level.PlayerChunkMap$$Lambda$5289/0x0000000801bb6000.apply(Unknown Source), java.base@17.0.4.1/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150), java.base@17.0.4.1/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482), app//net.minecraft.server.level.ChunkTaskQueueSorter.b(ChunkTaskQueueSorter.java:58), app//net.minecraft.server.level.ChunkTaskQueueSorter$$Lambda$5280/0x0000000801bb1690.run(Unknown Source), app//net.minecraft.util.thread.ThreadedMailbox.g(ThreadedMailbox.java:87), app//net.minecraft.util.thread.ThreadedMailbox.a(ThreadedMailbox.java:141), app//net.minecraft.util.thread.ThreadedMailbox.run(ThreadedMailbox.java:96), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Timer hack thread: [java.base@17.0.4.1/java.lang.Thread.sleep(Native Method), app//net.minecraft.SystemUtils$5.run(SystemUtils.java:610)], WAITING pool-18-thread-1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170), java.base@17.0.4.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Craft Async Scheduler Management Thread: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING ForkJoinPool-5-worker-11: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:410), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1726), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1623), java.base@17.0.4.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), app//com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:91), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE DestroyJavaVM: [], RUNNABLE Netty Epoll Server IO #0: [app//io.netty.channel.epoll.Native.epollWait(Native Method), app//io.netty.channel.epoll.Native.epollWait(Native.java:192), app//io.netty.channel.epoll.Native.epollWait(Native.java:185), app//io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989), app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE Signal Dispatcher: [],}
   
   Force Loaded Chunks: { world: {}, world_nether: {}, world_the_end: {}, cb1: { PlotSquared v6.9.4-Premium: 1,},}
	Player Count: 0 / 200; []
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```
### To Reproduce

plot regenallroads

### Expected behaviour

The error happened like this I made my roads around a GS made schmetica and enter the command plot regenallroads plot world in the console and the error comes

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e51a37679606431385ccdf4d0e8a87df

### PlotSquared Version

PlotSquared v6 6.9.4

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes #3801

### CODE REVIEW

File: Bukkit/src/main/java/com/plotsquared/bukkit/queue/LimitedRegionWrapperQueue.java [hunk 1]
```diff
@@ -44,6 +44,7 @@ public class LimitedRegionWrapperQueue extends DelegateQueueCoordinator {
     private static final Logger LOGGER = LogManager.getLogger("PlotSquared/" + LimitedRegionWrapperQueue.class.getSimpleName());
 
     private final LimitedRegion limitedRegion;
+    private boolean useOtherRestoreTagMethod = false;
```
Comment (SirYwell) [inline Bukkit/src/main/java/com/plotsquared/bukkit/queue/LimitedRegionWrapperQueue.java:47]: Can't we check the minecraft version here directly? (And in that case, the variable could be static final)

Comment (dordsor21) [reply Bukkit/src/main/java/com/plotsquared/bukkit/queue/LimitedRegionWrapperQueue.java:47]: We don't know that it definitely will or won't fail. I was working on the basis that we don't know for sure if it's an issue that will affect all 1.17.1 builds of spigot/paper

**Review by SirYwell — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
