### PR TITLE
fix: Standardize projectile permissions

### LINKED ISSUE #2986: Splash Potion Flag/Permission
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 
https://pastebin.com/HiJTMV6X

**Description of the problem:** 
Players can only throw splash potions if they are added or trusted to a plot, despite permissions and plot flags.

**How to replicate:** 

Create a plot and set no flags on it. Give all players the permission plots.projectile.other. You should find that players added to the plot can throw potions but players not added to the plot cannot, despite what the permission should do.

**Checklist**:

- [] I included a `/plot debugpaste` link (The command appears to be broken, I was instructed to link a startup log instead.)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by zombachu**
## Overview

Fixes #2986

## Description

- Let all projectiles (not just splash potions) have a permissions check on throwing
- Fixes snowballs, eggs, etc. being able to be thrown when not added to the plot, etc.
- Fixes #2986 (splash potions only able being to be thrown when also added to the plot)
- Remove the specialized code for egg hatching as now eggs are cancelled entirely
- Remove the non-standard plots.projectile.unowned and plots.projectile.other permissions in favor of the standard admin ones

## Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by NotMyFault** [comment]
Note (to myself): Include permission updates in the changelog and possibly add a maintainer checklist.

**Review by NotMyFault — APPROVED** [review]
Thanks for your contribution, finally sorting the mess 👏🏻

File: Core/src/main/java/com/plotsquared/core/permissions/Permission.java [hunk 1]
```diff
@@ -37,8 +37,6 @@
     PERMISSION_STAR("*"),
     PERMISSION_ADMIN("plots.admin"),
     PERMISSION_ADMIN_AREA_SUDO("plots.admin.area.sudo"),
-    PERMISSION_PROJECTILE_UNOWNED("plots.projectile.unowned"),
-    PERMISSION_PROJECTILE_OTHER("plots.projectile.other"),
```
Comment (SirYwell) [inline Core/src/main/java/com/plotsquared/core/permissions/Permission.java:41]: Those should only marked as deprecated for removal.

**Review by SirYwell — CHANGES_REQUESTED** [review]
Looks good overall

File: Core/src/main/java/com/plotsquared/core/permissions/Permission.java (hunk 1 above)
Comment (zombachu) [reply Core/src/main/java/com/plotsquared/core/permissions/Permission.java:41]: While deprecated should they essentially be an alias for the admin versions or should they not be linked up to anything at all (and only exist in `Permission` I guess)?

Comment (SirYwell) [reply Core/src/main/java/com/plotsquared/core/permissions/Permission.java:41]: Leaving it there unused would be the best I think

File: Core/src/main/java/com/plotsquared/core/permissions/Permission.java [hunk 2]
```diff
@@ -37,7 +37,9 @@
     PERMISSION_STAR("*"),
     PERMISSION_ADMIN("plots.admin"),
     PERMISSION_ADMIN_AREA_SUDO("plots.admin.area.sudo"),
+    @Deprecated(forRemoval = true)
     PERMISSION_PROJECTILE_UNOWNED("plots.projectile.unowned"),
+    @Deprecated(forRemoval = true)
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/permissions/Permission.java:42]:
```suggestion
    @Deprecated(forRemoval = true, since = "6.3.0")
    PERMISSION_PROJECTILE_UNOWNED("plots.projectile.unowned"),
    @Deprecated(forRemoval = true, since = "6.3.0")
```

**Review by Citymonstret — APPROVED** [review]
LGTM

**Comment by NotMyFault** [comment]
We may merge it in 24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

I've taken some notes about the permission update I'll feed into release drafter by hand.
