### PR TITLE
Features/v5/move swap fixes + some other important commits (comments, etc)

### LINKED ISSUE #2282: BUG /plot swap returns the original plot owners after restart
**Debug paste link:**
https://incendo.org/paste/view/0dd2befb90b54ed78b91c8b43209d5c9

**Description of the problem:** 
I tested a few times to make sure. /plot swap works fine and swaps the plots and owners, but after a restart, it unswaps the owners of the plot. This is an old issue that was closed and now reopened.
I have not tested this on 1.13

**How to replicate:** 
Use /plot swap on different plot owners. Then restart the server and you'll see it unswaps the plot owners.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by Sauilitired**
## Overview

**Fixes #2282, #2603**

## Description
This PR makes sure that plot owners are swapped properly. It also makes sure to clear the 
plot on plot move (previously it just left the intact, but unclaimed). Furthermore, swapping
now updates the signs.

Some changes to the API were made, namely to make swapping and moving rely on
futures. 

The merge also includes other commits from v4, such as the `/plot comment` fix. 

## Checklist

- [X] I included all information required in the sections above
- [X] I tested my changes and approved their functionality
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/breaking/CONTRIBUTING.md)

### CODE REVIEW

File: Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java [hunk 1]
```diff
@@ -3076,18 +3070,18 @@ public boolean move(final Plot destination, final Runnable whenDone, boolean all
         final int offsetZ = db.getZ() - ob.getZ();
         if (this.owner == null) {
             TaskManager.runTaskLater(whenDone, 1);
-            return false;
+            return CompletableFuture.completedFuture(false);
         }
-        boolean occupied = false;
+        AtomicBoolean occupied = new AtomicBoolean(false);
         Set<Plot> plots = this.getConnectedPlots();
```
Comment (dordsor21) [inline Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java]: Why are we swapping connected plots if we're not allowing moving/swapping of connected plots?

Comment (Sauilitired) [reply Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java]: I didn't really want to remove the code, although it can be removed without consequences so I guess it'd be a good idea to.

Comment (Sauilitired) [reply Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java]: But also, there's no real harm in allowing the code to swap merged plots. We just disallow it in the command as it's not something we really want to support, kind of.

File: Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/block/GenChunk.java [hunk 2]
```diff
@@ -109,7 +110,7 @@ public boolean setBiome(int x, int z, Biome biome) {
     }
 
     @Override public boolean setBlock(int x, int y, int z, @NotNull Pattern pattern) {
-        return setBlock(x, y, z, PatternUtil.apply(pattern, x, y, z));
+        return setBlock(x, y, z, PatternUtil.apply(Preconditions.checkNotNull(pattern, "Pattern may not be null"), x, y, z));
```
Comment (MattBDev) [inline Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/block/GenChunk.java]: It shouldn't be null anyways because of the annotation we have on this method.

Comment (Sauilitired) [reply Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/util/block/GenChunk.java]: It was null when the patterns failed to parse and it was really hard to track down.
