### PR TITLE
fix: replace usages of snow tag

### LINKED ISSUE #3757: "SNOW" doesn't exist on 1.16.5 as tag name
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

[17:11:47 ERROR]: Could not pass event BlockFadeEvent to PlotSquared v6.9.3-Premium
java.lang.NoSuchFieldError: SNOW
        at com.plotsquared.bukkit.listener.BlockEventListener.onFade(BlockEventListener.java:681) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor57.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockFadeEvent(CraftEventFactory.java:807) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.BlockDirtSnowSpreadable.tick(BlockDirtSnowSpreadable.java:48) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.b(BlockBase.java:622) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:825) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:872) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:683) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:850) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:767) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:576) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

-

### Expected behaviour

-

### Screenshots / Videos

-

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/293ba987968c4e319e1abbb89c4215a0

### PlotSquared Version

PlotSquared v6.9.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

-

### PR DESCRIPTION
**Pull request by SirYwell**
## Overview

Fixes #3757

## Description

The `snow` tag was only added with Minecraft 1.17, therefore we can't use it directly.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Untested, but looks reasonable.

**Comment by SirYwell** [comment]
Had to change that again, now it works.

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java [hunk 1]
```diff
@@ -121,6 +121,23 @@ public class BlockEventListener implements Listener {
...
+            );
+        } else {
+            SNOW = Set.of(
+                    Material.SNOW,
+                    Material.SNOW_BLOCK,
+                    Material.POWDER_SNOW // only since 1.17
+            );
+        }
+    }
+
```
Comment (PierreSchwang) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:140]: I personally would be a bigger fan of something like 
```
private static final Set<Material> SNOW_BLOCKS = Stream.of(Material.values())
            .filter(material -> material.name().contains("SNOW"))
            .filter(Material::isBlock)
            .collect(Collectors.toSet());
```
Maintainability would be better in that case, as static collections like that might get lost and forgot on updates. The only problems I've found on my testing is, that the cauldron filled with powedered snow ([SNOW_BLOCK, **POWDER_SNOW_CAULDRON**, POWDER_SNOW, SNOW]) is present in that set as well. But I don't think that's that big of an issue, as that block wouldn't call the BlockFormEvent.

**Review by PierreSchwang — APPROVED** [review]
Just one thing I'd find better, but doesn't have to be addressed - just an opinion

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java (hunk 1 above)
Comment (MattBDev) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:140]: > Maintainability would be better in that case, as static collections like that might get lost and forgot on updates.
I like that it would be more maintainable but I am not a big fan of it iterating over all the materials just for snow blocks.
That being said, it is the most maintainable solution and readable so I am fine with either Pierre or SirYwell's solution.

Comment (NotMyFault) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:140]: @PierreSchwang is this blocking feedback? As indicated by your approval, I'd say the opposite.

Comment (PierreSchwang) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:140]: Nope, as I said this would just be an opinion how it could potentially be more future proof. But I approved nevertheless, as this can be merged either way. Would've appreciate an opinion by Kalle tho
