### PR TITLE
Plotowner are kicked at "/p deny *" themselves

### LINKED ISSUE #2696: Plotowner are kicked at "/p deny *" themselves
# Bug Report Template:

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [x] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [x] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [x] Minecraft 1.14.4
- [x] Minecraft 1.13.2
- [x] Minecraft Java Edition *other versions, please specify*:
- [x] Minecraft Bedrock Edition *specify version*:

### Description of the problem:
Plotowner are kicked at "/p deny *" themselves.

### How to replicate:
Enter "/p deny *" as Plotowner on a plot

# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

### PR DESCRIPTION
**Pull request by hyWse**
## Overview

**Fixes #2696**

## Description
Plotowner are kicked at "/p deny *" themselves.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/breaking/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dordsor21** [comment]
If this is being fixed, it should also prevent players that have been added/trusted from being kicked, as the plot deny * effectively creates a whitelist using added players.

See: https://github.com/IntellectualSites/PlotSquared/blob/49cd8baa27fdbf65872a6e14f96784b9c373eade/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/object/Plot.java#L484

File: Core/src/main/java/com/github/intellectualsites/plotsquared/plot/commands/Deny.java [hunk 1]
```diff
@@ -74,6 +74,10 @@ public Deny() {
                 handleKick(UUIDHandler.getPlayer(uuid), plot);
             } else {
                 for (PlotPlayer plotPlayer : plot.getPlayersInPlot()) {
+                    // Ignore plot-owners
+                    if (plot.isOwner(plotPlayer.getUUID())) {
```
Comment (Sauilitired) [inline Core/src/main/java/com/github/intellectualsites/plotsquared/plot/commands/Deny.java]: use `Plot#isAdded`

**Comment by hyWse** [comment]
Done
