### PR TITLE
fix: NPE on unavailable music discs on lower versions

### LINKED ISSUE #3454: NPE when trying to use /plot music
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using /plot music you get an internal error message ingame and a NPE in the console.
Once this happened any other try of /plot music results in nothing happening at all until you relog.

### To Reproduce

Log on,
Typ /plot music,
Error.

### Expected behaviour

I expect it to open a music selection interface and to play some music in the plot.

### Screenshots / Videos

-

### Error log (if applicable)

https://pastebin.com/F8jYM2ny

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/320daa712822401aa94acd4f96acdc00

### PlotSquared Version

6.3.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview

Fixes #3454 

## Description
Respect unavailable music discs from newer versions by checking there existence in Bukkits Item API.
Now setItem returns a boolean wheter an item could be set into the inventory (currently returns true, if the material exists, otherwise false). 
Invalid music discs are now skipped in `/plot music`

As the signature changed from void -> boolean that is no breaking change in api usage.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

File: Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java [hunk 1]
```diff
@@ -103,9 +103,12 @@ public void close() {
         this.open = false;
     }
 
-    public void setItem(int index, PlotItemStack item) {
+    public boolean setItem(int index, PlotItemStack item) {
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:106]: Nevertheless we could put javadocs and since here I guess?

File: Core/src/main/java/com/plotsquared/core/plot/PlotItemStack.java [hunk 2]
```diff
@@ -46,7 +46,20 @@ public PlotItemStack(
...
     ) {
-        this.type = ItemTypes.get(id);
+        this(ItemTypes.get(id), amount, name, lore);
+    }
+
+    /**
+     * @param type   The item type
+     * @param amount Amount of items in the stack
+     * @param name   The display name of the item stack
+     * @param lore   The item stack lore
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/plot/PlotItemStack.java:56]: May place a since tag here as well.

**Review by NotMyFault — COMMENTED** [review]
But works well, tested on 1.17.1

File: Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java (hunk 1 above)
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:106]: @\inheritDoc should do the job i guess?

Comment (NotMyFault) [reply Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:106]: From where do you want to inherit it from? This method is not overridden or delegated via super. 👀

Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:106]: Oh wait, wrong file, my bad lmao

File: Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java [hunk 3]
```diff
@@ -103,9 +103,20 @@ public void close() {
...
     }
 
-    public void setItem(int index, PlotItemStack item) {
+    /**
+     * Put an item into this inventory
+     *
+     * @param index the index (= slot) where to place the item
+     * @param item  the item to place
+     * @return {@code true} if the item could be placed, otherwise {@code false}
+     * @see InventoryUtil#setItem(PlotInventory, int, PlotItemStack)
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:112]: Missing since tag

Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:112]: The method is not new at all, just changed the signature from void to boolean, or should that be commented with the since tag?

Comment (NotMyFault) [reply Core/src/main/java/com/plotsquared/core/plot/PlotInventory.java:112]: No, looks like IJ just rendered it weird. Dismiss.

**Review by NotMyFault — APPROVED** [review]
Tested on 1.17.1, works great 👏🏻 

Other inventories, like the rating GUI or `/plot components` are not impacted by this change.

File: Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java [hunk 4]
```diff
@@ -104,14 +109,19 @@ public void close(PlotInventory inv) {
     }
 
     @Override
-    public void setItem(PlotInventory inv, int index, PlotItemStack item) {
+    public boolean setItem(PlotInventory inv, int index, PlotItemStack item) {
```
Comment (dordsor21) [inline Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java:112]: Is it not a breaking change as the signature of the method changing will make it unable to be compiled against for previous versions?

Comment (SirYwell) [reply Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java:112]: Compiling would be fine but this is a binary incompatible change.

Comment (dordsor21) [reply Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitInventoryUtil.java:112]: Yeah I worded that really poorly. We should make a new method that returns boolean setItemAndReturn or setItemAndCheck or something and deprecate the old one (or leave and add javadoc note on the super method regarding this

**Review by dordsor21 — APPROVED** [review]

**Comment by NotMyFault** [comment]
@SirYwell Do you want to take an additional look again?

**Review by SirYwell — APPROVED** [review]
