### PR TITLE
Ensure forceSync is provided when constructing chunk coordinators

### LINKED ISSUE #3667: Async catcher prevents plot clear
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Async catcher prevents plot clearing on 1.19

### To Reproduce

- Create a server on 1.19 using the newest Paper, WorldEdit and P2 build (specific version information can be obtained from the debugpaste below)
- Create a plot world
- Run `/plot clear`

### Expected behaviour

Proceed fine

### Screenshots / Videos

_No response_

### Error log (if applicable)

https://gist.github.com/NotMyFault/e78359794d04f904e38a7af8cb3cb768

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/355edd9b906d4cc9bba7d87ed6b562e0

### PlotSquared Version

6.8.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dordsor21**
- Fixes asyncCatchOp errors due to chunk coordinators defaulting to forceSync "true"
 - Details that forceSync is *not* necessarily synchronous to the server main thread, and instead sets that enqueue/start methods are synchronous (blocking)
 - Fixes #3667

### CODE REVIEW

File: Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinatorBuilder.java [hunk 1]
```diff
@@ -227,7 +240,8 @@ public ChunkCoordinatorBuilder(@NonNull ChunkCoordinatorFactory chunkCoordinator
                         this.whenDone,
                         this.throwableConsumer,
                         this.unloadAfter,
-                        this.progressSubscribers
+                        this.progressSubscribers,
+                        this.forceSync
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/queue/ChunkCoordinatorBuilder.java:244]: It would make sense to deprecate the existing builder and create a new method, because it's API, which now takes an additional parameter.

**Review by SirYwell — APPROVED** [review]
