### PR TITLE
Respect non-visible players in tab completion (Closes #3263)

### LINKED ISSUE #3263: Hide vanished players from tab completion on disabled usercache
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i go in vanish, players can see my name on /p v so players can see that iam online

### To Reproduce

1. Go in vanish Using some vanish plugin or player.hide()
2. Use 2th acc with no perms to check /p v

### Expected behaviour

Vanished players should be not visible in the tab complete

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/5d599ac2170542699edb7b59f1fbf983

### PlotSquared Version

6.1.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

It would be nice if support for vanish plugins can be added like PremiumVanish

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
**Fixes https://github.com/IntellectualSites/PlotSquared/issues/3263**

## Description
Tabcompletions for PlotSquared now respects Bukkits Player#canSee (platform independent: PlotPlayer#canSee) to ensure only visible players are recommended using tab completion.

Changes signatures:
- `TabCompletions.completePlayers(String, List<String>)` -> `completePlayers(PlotPlayer<?>, String, List<String>)` 
- `TabCompletions.completePlayers(String, String, List<String>, Predicate<UUID>)` -> `completePlayers(String, PlotPlayer<?>, String, List<String>, Predicate<UUID>) `
- `TabCompletions.completeAddedPlayers(Plot, String, List<String>)` -> `completePlayers(PlotPlayer<?>, Plot, String, List<String>)` 

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/PlotSquared/blob/v6/CONTRIBUTING.md)

### CODE REVIEW

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java [hunk 1]
```diff
@@ -78,29 +78,33 @@ private TabCompletions() {
      * cache, so it will complete will all names known to PlotSquared
      *
      * @param input    Command input
+     * @param issuer   The player who issued the tab completion
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:81]: Instead of breaking existing methods, deprecating and scheduling them for removal while pointing to the newer ones is preferred.

**Review by NotMyFault — CHANGES_REQUESTED** [review]

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java (hunk 1 above)
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:100]: Old methods are present again and deprecated

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java [hunk 2]
```diff
@@ -73,34 +74,73 @@ private TabCompletions() {
...
+    /**
+     * Get a list of tab completions corresponding to player names. This uses the UUID pipeline
+     * cache, so it will complete will all names known to PlotSquared
+     *
+     * @param input    Command input
+     * @param existing Players that should not be included in completions
+     * @return List of completions
+     * @deprecated In favor {@link #completePlayers(PlotPlayer, String, List)}
+     */
+    public static @NonNull List<Command> completePlayers(
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:88]: We are using Java 16, so we can mark this for removal.

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java [hunk 3]
```diff
@@ -73,34 +74,73 @@ private TabCompletions() {
                 "This is a utility class and cannot be instantiated");
     }
 
+
+
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:78]: One is enough.

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java [hunk 4]
```diff
@@ -73,34 +74,73 @@ private TabCompletions() {
...
+    /**
+     * Get a list of tab completions corresponding to player names added to the given plot.
+     *
+     * @param plot     Plot to complete added players for
+     * @param input    Command input
+     * @param existing Players that should not be included in completions
+     * @return List of completions
+     *
+     * @deprecated In favor {@link #completeAddedPlayers(PlotPlayer, Plot, String, List)}
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:120]: See former comment

**Review by NotMyFault — CHANGES_REQUESTED** [review]
Otherwise, looking good

**Review by NotMyFault — APPROVED** [review]

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java [hunk 5]
```diff
@@ -222,9 +262,28 @@ private TabCompletions() {
...
+     * @param cacheIdentifier Cache key
+     * @param issuer          The player who issued the tab completion
+     * @param input           Command input
+     * @param existing        Players that should not be included in completions
+     * @param uuidFilter      Filter applied before caching values
+     * @return List of completions
      */
     private static List<Command> completePlayers(
             final @NonNull String cacheIdentifier,
+            final @Nullable PlotPlayer<?> issuer,
```
Comment (SirYwell) [inline Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:286]: Would it make sense to make the issuer NonNull too and use the console (`ConsolePlayer.getConsole()`) as default in the old methods instead?

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: Core/src/main/java/com/plotsquared/core/util/TabCompletions.java (hunk 5 above)
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:286]: Sure, I can do that. It doesn't change the logic behind it, it's just a pure API design choice. I don't know how you handle this.

Comment (SirYwell) [reply Core/src/main/java/com/plotsquared/core/util/TabCompletions.java:286]: Commands are always executed with an issuer, but making it Nullable could indicate otherwise. So yeah, I'd prefer to make it NonNull

**Review by SirYwell — APPROVED** [review]
Thank you
