### PR TITLE
Items no longer despawn on road when natural_mob_spawning = true and kill-road-items = false

### LINKED ISSUE #3725: Items disappear on the street when setting `natural_mob_spawning` to true
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If you have naturlal_mob_spawning enabled in worlds.yml, items dropped from player inventory will despawn on roads and unoccupied plots.

### To Reproduce

words.yml
natural_mob_spawning: true
go to street or unoccupied plots
try to drop items

### Expected behaviour

Apparently the Killing Road Items setting is affected.

### Screenshots / Videos

_No response_

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/431b71b7797d45439b64c8cd6ebcd816

### PlotSquared Version

6.9.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #3725 

## Description
EntitySpawnEvent is now cancelled correctly

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java [hunk 1]
```diff
@@ -140,6 +140,12 @@ public void creatureSpawnEvent(EntitySpawnEvent event) {
                     event.setCancelled(true);
                 }
             }
+            if (type == EntityType.DROPPED_ITEM) {
+                if (Settings.Enabled_Components.KILL_ROAD_ITEMS) {
+                    event.setCancelled(true);
+                }
+                return;
+            }
```
Comment (SirYwell) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java:148]: This is basically just duplicated with the code a few lines above. I think we can just put it above the `!area.isMobSpawning()` check.

Also note that there is very similar code in `PaperListener` which should probably updated too.

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java (hunk 1 above)
Comment (PierreSchwang) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java:148]: Nope, the CreatureSpawnEvent is not called, therefor the PaperListener does not need any update
Tested my changes on paper, and it did work

Comment (SirYwell) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntitySpawnListener.java:148]: I think it would still make sense to keep them consistent, otherwise that might be confusing in future (as the code isn't documented at all anyways).

**Review by SirYwell — APPROVED** [review]
Looks good.

**Review by NotMyFault — APPROVED** [review]
