### PR TITLE
Fix: Missing Component returns + plot info on unknown plot owner

### LINKED ISSUE #3443: Unknown plots not responding to any commands
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I have a strange problem with an old plotworld (many years old), where hundreds of plots on the world are empty, in claimed state and have 'Owner: unknown'.

If I type commands such as `/plot info` while standing on the plot, nothing happens, no error in the console. If I type a command like `/plot claim` while standing on a broken plot, it will say "This plot is already claimed".

I have tried running the plugin with `uuid-cache-size: 0` and `uuid-cache-size: 100000`

I also tried disabling all UUID services except luckperms (in case one of them was giving bad data?):
``` 
  # Whether the PaperMC service is enabled
  service-paper: false
  # Whether the LuckPerms service is enabled
  service-luckperms: true
  # Whether the Bukkit service is enabled
  service-bukkit: false
  # Whether the EssentialsX service is enabled
  service-essentialsx: false
```

### To Reproduce

Not exactly sure how to suggest reproducing this. I'm happy to assist in trying different fixes on the live server.

Here are the database files:
**storage.db**
https://www.dropbox.com/s/w6yzi07hcbz3plc/storage.db?dl=0
**user_cache.db**
https://www.dropbox.com/s/rrku5ymlv4tgr4b/user_cache.db?dl=0

### Expected behaviour

The plot should recognize it's owner and be loaded in properly.

Most of these plots are empty and by inactive players, so this bug is stopping them from being purged for inactivity.

### Screenshots / Videos

image

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9d6f87b791a34424bea841ccca6812d3

### PlotSquared Version

PlotSquared version 6.2.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview

Fixes #3443 

## Description
d3fe1d3b2bab02a7e1ef66d3c69d0cfa49d65f26 introduced an issue now known as https://github.com/IntellectualSites/PlotSquared/issues/3443
That was due to a incorrect locale, which should've thrown an exception, but that happened in another thread and just halted the whole thread.
That happened because of missing player data in bukkits storage, documentation from OfflinePlayer#getLastSeen:
> Gets the last date and time that this player was seen on the server.
> If the player has never played before, this will return 0.

That would also explain https://github.com/IntellectualSites/PlotSquared/issues/3006, as the mentioned method is used to determine the last online time of all plot owners. if that is equal to 0, nothing will be deleted: https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/plot/expiration/ExpireManager.java#L229. That should be changed.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 1]
```diff
@@ -164,25 +164,51 @@ public static void getUUIDsFromString(
      * @return The player's name, None, Everyone or Unknown
      */
     public static @NonNull String getName(final @Nullable UUID owner) {
-        return getName(owner, true);
+        return getName(owner, LocaleHolder.console());
```
Comment (dordsor21) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:167]: Might be best to default to null here and deprecate the method, or state that no messages will be sent in the JD comments above. If someone is accessing the method from another plugin and suddenly start getting console output from it, it'll be a little confusing

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 2]
```diff
@@ -164,25 +164,51 @@ public static void getUUIDsFromString(
...
     /**
      * Get the name from a UUID.
      *
      * @param owner    Owner UUID
-     * @param blocking Whether or not the operation can be blocking
+     * @param blocking Whether the operation can be blocking
      * @return The player's name, None, Everyone or Unknown
      */
     public static @NonNull String getName(final @Nullable UUID owner, final boolean blocking) {
+        return getName(owner, LocaleHolder.console(), blocking);
```
Comment (dordsor21) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:189]: Same as above

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 3]
```diff
@@ -164,25 +164,51 @@ public static void getUUIDsFromString(
...
+     * @param blocking     Whether the operation can be blocking
+     * @return The player's name, None, Everyone or Unknown
+     */
+    public static @NonNull String getName(
+            final @Nullable UUID owner, final @NonNull LocaleHolder localeHolder,
+            final boolean blocking
+    ) {
         if (owner == null) {
-            TranslatableCaption.of("info.none");
+            return TranslatableCaption.of("info.none").getComponent(localeHolder);
```
Comment (dordsor21) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:205]: Rather than returning the error string, might be better just to send the error message directly to the player, and adjust this method and its callees by returning null or empty? The previous behaviour was returning null after all

Comment (SirYwell) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:205]: The previous behaviour basically ignored the `@NonNull` contract and was wrong therefore. Changing a method from `@NonNull` to `@Nullable` changes its contract in an unsafe manner and should be avoided.

Directly sending the message from this method should be avoided, because that method can be used to show the name in separate places: embedded in different messages, sent as action bar, etc.

That said, the method should probably be deprecated, with a new method returning a `Caption`. This way, the `LocaleHolder` is not required here. WDYT?

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java (hunk 1 above)
Comment (NotMyFault) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:167]: Yeah, deprecating the current methods and introduce new ones are the better way to go.

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java (hunk 3 above)
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:205]: I mean, the contract is already not fullfilled. Until now, `return name` is called in either case, even if name is null.

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 4]
```diff
@@ -203,6 +209,57 @@ public static void getUUIDsFromString(
...
 
+    /**
+     * Attempts to resolve the username by an uuid
+     * <p>
+     * <b>Note:</b> blocks the thread until the name was resolved or failed
+     *
+     * @param owner The UUID of the owner
+     * @return A caption containing either the name, {@code None}, {@code Everyone} or {@code Unknown}
+     * @see #resolveName(UUID, boolean)
+     * @since 6.2.3
```
Comment (NotMyFault) [inline Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:220]: That'd be 6.3.0 then, considering this is hardly a patch for 6.2. But you can also use `@since TODO`, I have a script that injects the parsed version from `build.gradle.kts` if I publish releases.

**Review by NotMyFault — APPROVED** [review]

**Review by SirYwell — APPROVED** [review]

**Comment by NotMyFault** [comment]
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java [hunk 5]
```diff
@@ -173,7 +177,9 @@ public static void getUUIDsFromString(
      * @param owner    Owner UUID
      * @param blocking Whether or not the operation can be blocking
      * @return The player's name, None, Everyone or Unknown
+     * @deprecated Use {@link #resolveName(UUID, boolean)}
      */
+    @Deprecated(forRemoval = true, since = "TODO")
```
[the remark this answers is not in the document]
Comment (NotMyFault) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:182]: Is there something wrong with the TODO here?

[the remark this answers is not in the document]
Comment (PierreSchwang) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:182]: It's a post-merge thing https://github.com/IntellectualSites/PlotSquared/pull/3449#discussion_r783457457

**Review by dordsor21 — APPROVED** [review]

File: Core/src/main/java/com/plotsquared/core/util/PlayerManager.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (NotMyFault) [reply Core/src/main/java/com/plotsquared/core/util/PlayerManager.java:182]: > Can/should it not be replaced with the version? Or is that a post-merge thing

Yeah, I replace `@since TODO` with the version released. Using the current version can lead to conflicts or doesn't display the appropriate version, e.g. if this TODO is 1.2.1 but another PR merged would bump to 1.3.0, we would have to address the 1.2.1 ones post merge, do it on the other PR or let the PR author do it; generally introduces more work and more to take core of, instead of simply replacing TODOs when doing releases.
