### PR TITLE
Cancel block placement if the block consists of two block states

### LINKED ISSUE #3483: Beds can be placed on the borders of plots
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If you place a bed on the very edge of a plot and it's facing the road it will be placed onto the border like this and then the part facing the road can't be broken: https://cdn.discordapp.com/attachments/937052608470847508/937052702003830834/2022-01-29_17.52.42.png

A fix would probably be to either prevent the bed from being placed entirely or only placing half of it and removing the other half.
I also think beds are the only blocks/items in Minecraft that work like this.
It's not a huge problem but something to maybe fix at some point :)

### To Reproduce

See above

### Expected behaviour

See above

### Screenshots / Videos

https://cdn.discordapp.com/attachments/937052608470847508/937052702003830834/2022-01-29_17.52.42.png

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/83eb112254d04ca88632c4ec74b063a7

### PlotSquared Version

6.4.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview

Fixes #3483

## Description
Cancels block placement if the block consists of two block states, and the second block state is outside of the plot (area).
Additionally cancelled the placement of doors, when the upper part exceeds the height limit of the current plot area.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] I tested my changes and approved their functionality.
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

## Maintainer checklist

Before the changes are marked as `Ready for merge`: 

- [ ] There are at least 2 approvals from project developers or maintainers for the pull request and no outstanding requests for change
- [ ] Conversations in the pull request are over OR it is explicit that a reviewer does not block the change
- [x] Changelog entries in the PR title are correct
- [x] Proper changelog labels are set so that the changelog can be generated automatically
- [ ] If the change needs additional modification steps from users, e.g. for permission changes, make sure the entry is added to the pull request description so it can be appended to the changelog.

### CODE REVIEW

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java [hunk 1]
```diff
@@ -324,6 +326,30 @@ public void blockCreate(BlockPlaceEvent event) {
...
+                if (!(Objects.equals(BukkitUtil.adapt(other).getPlot(), plot))) {
+                    pp.sendMessage(
+                            TranslatableCaption.of("permission.no_permission_event"),
+                            Template.of("node", String.valueOf(Permission.PERMISSION_ADMIN_BUILD_ROAD))
+                    );
+                    event.setCancelled(true);
+                    return;
+                }
+            }
+            // Same goes for doors, which may exceed the area height limit
```
Comment (NotMyFault) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:341]: Good catch with the doors! Though I can imagine that the same applies to more items? E.g. horizontally placed item frames or trees grown from bonemeal interaction?

Comment (PierreSchwang) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:341]: I couldn't think about more items witch multiple block states - If you have a list of all blocks and interactions I could try to implement those

Comment (NotMyFault) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:341]: I created a new issue to not clutter this PR, considering it's somewhat out of the scope of this PR https://github.com/IntellectualSites/PlotSquared/issues/3488
Would be cool if you would want to work on it 👍🏻

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java [hunk 2]
```diff
@@ -324,6 +326,30 @@ public void blockCreate(BlockPlaceEvent event) {
...
+            if (event.getBlock().getBlockData() instanceof Door door) {
```
Comment (dordsor21) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:342]: Assumedly there isn't a utility method for checking the block "size"?

Comment (PierreSchwang) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:342]: Haven't found anything there sadly. There is the Directional interface, but that doesn't indicate that the block contains more than one block state at a time.

Comment (dordsor21) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:342]: Just remembered that there's this event https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockMultiPlaceEvent.html

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java [hunk 3]
```diff
@@ -1208,4 +1210,51 @@ public void onSpongeAbsorb(SpongeAbsorbEvent event) {
         }
     }
 
+    /*
+     * BlockMultiPlaceEvent is called unrelated to the BlockPlaceEvent itself and therefor doesn't respect the cancellation.
```
Comment (dordsor21) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:1214]: typo, therefore*

File: Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java [hunk 4]
```diff
@@ -1208,4 +1210,51 @@ public void onSpongeAbsorb(SpongeAbsorbEvent event) {
...
+                        TranslatableCaption.of("permission.no_permission_event"),
+                        Template.of("node", String.valueOf(Permission.PERMISSION_ADMIN_BUILD_ROAD))
+                );
+                event.setCancelled(true);
+                break;
+            }
+            if (Permissions.hasPermission(pp, Permission.PERMISSION_ADMIN_BUILD_HEIGHT_LIMIT)) {
+                continue;
+            }
+            if (currentLocation.getY() > area.getMaxBuildHeight() || currentLocation.getY() < area.getMinBuildHeight()) {
```
Comment (dordsor21) [inline Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:1248]: the over-max-height should be a greater-equal as max build height is exclusive

Comment (PierreSchwang) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:1248]: Unlikely, as the remaining checks are compared using greater as well 
grafik

Comment (dordsor21) [reply Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java:1248]: That's an error in those locations then

**Review by dordsor21 — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.
