### PR TITLE
Road-Schematic-Generation now shows correct skull skins and banner patterns

### LINKED ISSUE #4003: World Generator does not set banner and head data.
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

I have an road template that includes banners with patterns and heads with skins stored in the meta.
When using the world generator to generate new chunks the banner patterns and the skin stored in player heads is missing.

But if u regen the roads via: /p debugroadgen the banner patterns / head skins are loading correctly.

### To Reproduce

1. Craeate an 1.19.3 or 1.19.4 server with the newest build.
2. Put Plotsqared 6.11.1 on it.
3. Crate an Road-schem that has an playerhead (via head-db) and an banner with an pattern on it.
4. (Otional) Restart the server
5. Fly a bit into ungenerated chucks and check the hats and banners

### Expected behaviour

The Road schem loading as it was saved.

### Screenshots / Videos

https://i.imgur.com/LPze9BP.png
https://i.imgur.com/lhSVzHK.png

### Error log (if applicable)

_No response_

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9e3f74b63496437a9728ed03c913b88a

### PlotSquared Version

6.11.1-Snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

We use a self-build snapshot build on our dev-server

### PR DESCRIPTION
**Pull request by PierreSchwang**
## Overview
Fixes #4003

## Description
Fixes missing NBT data for banners and some skulls on road generation

+ Added Banners to StateWrapper
+ Supported custom Textures in StateWrapper for Skulls (only on paper)

Would appreciate further testing, only tested on Paper 1.19.4 (tho, I don't really care about older version to be completely honest)

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dordsor21 — APPROVED** [review]

File: Bukkit/src/main/java/com/plotsquared/bukkit/schematic/StateWrapper.java [hunk 1]
```diff
@@ -227,15 +240,65 @@ public boolean restoreTag(@NonNull Block block) {
...
+                    }
+                    String textureValue = textureCompound.getString("Value");
+                    if (textureValue == null) {
+                        return false;
+                    }
+                    if (!PaperLib.isPaper()) {
+                        if (!paperErrorTextureSent) {
+                            paperErrorTextureSent = true;
+                            LOGGER.error("Failed to populate skull data in your road schematic - Please use Paper to correctly " +
+                                    "generate skulls in your road schematics!");
```
Comment (NotMyFault) [inline Bukkit/src/main/java/com/plotsquared/bukkit/schematic/StateWrapper.java:274]:
```suggestion
                            LOGGER.error("Failed to populate skull data in your road schematic - This is a Spigot limitation."
```

**Review by NotMyFault — COMMENTED** [review]
Otherwise, LGTM

**Review by NotMyFault — APPROVED** [review]
